language: python
python:
    - '2.7'
script: ./setup.py test

install:
    - sudo apt-get install g++-4.8

addons:
    apt:
        packages:
            gcc-4.8
            g++-4.8
            clang
