language: cpp
compiler:
    - clang
script: ./setup.py test

sudo: false
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - clang

install:
    - export CFLAGS='-g -O0 --coverage'
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

after_success:
    - bash <(curl -s https://codecov.io/bash)

# it takes ages to compile v8 so don't do it too often
cache:
    directories:
        v8
