language: python
python:
    - '2.7'
script: ./setup.py test

sudo: false
addons:
    sources:
        - ubuntu-toolchain-r-test
    apt:
        packages:
            - gcc-4.8
            - g++-4.8
            - clang
