language: cpp
compiler:
    - gcc
script: ./setup.py test

sudo: false
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8

install:
    - ./build-v8.sh
    - ls v8/out/native
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

# it takes ages to compile v8 so don't do it too often
cache:
    directories:
        v8
