
language: python
sudo: false
group: beta
dist: xenial
services:
    - docker

jobs:
    include:
        - python: 2.7
          env:
            - CIBW_BUILD=cp27-manylinux_x86_64
            - CIBW_MANYLINUX_X86_64_IMAGE=quay.io/pypa/manylinux2014_x86_64:2020-07-27-669fac3
        - python: 3.5
          env:
            - CIBW_BUILD=cp35-manylinux_x86_64
            - CIBW_MANYLINUX_X86_64_IMAGE=quay.io/pypa/manylinux2014_x86_64:2020-07-27-669fac3
        - python: 3.6
          env:
            - CIBW_BUILD=cp36-manylinux_x86_64
            - CIBW_MANYLINUX_X86_64_IMAGE=quay.io/pypa/manylinux2014_x86_64:2020-07-27-669fac3
        - python: 3.7
          env:
            - CIBW_BUILD=cp37-manylinux_x86_64
            - CIBW_MANYLINUX_X86_64_IMAGE=quay.io/pypa/manylinux2014_x86_64:2020-07-27-669fac3
        - python: 3.8
          env:
            - CIBW_BUILD=cp38-manylinux_x86_64
            - CIBW_MANYLINUX_X86_64_IMAGE=quay.io/pypa/manylinux2014_x86_64:2020-07-27-669fac3

install:
    - pip install twine pytest greenstack cibuildwheel
    - export CFLAGS='-g -O0 --coverage'

script:
    - travis_wait 60 cibuildwheel --platform linux --output-dir dist
    - pip install dist/*.whl
    - pytest
    - pip uninstall -y greenstack && python -c "import v8py"


# it takes ages to compile v8 so don't do it too often
cache:
    directories:
        - v8

after_success:
    - bash <(curl -s https://codecov.io/bash)

deploy:
    provider: pypi
    user: tbodt
    password:
        secure: TeSSoX1sjprFbi3BbK7vDNVXzM/nSxxbcVyxF0Itvu0jqSWQhcRvtEr74wdW4nTyNTBxlfY1+HbDqwvNeADb+kyaQdlzlR/zQ2V3GCQ5muN0R8Lslfi+EI5rMf/h1pNuPxSm6yYA4qogN3QMEY9CiUgOmSG7RGsAXtgMLR48h9qQ0UNCTW/DqozKFD5HIi8os0HoURFtJRPafXLsRbJS8StRZmEjQDvsrfcMYxwlLsNikbfSR8TvBbztEum4mi5OqLl9Jbz0QH4sqfxhouvikXDxZlWYMdPZOuEzXBfDrMWCJXGIekSbQQ14N/j2PDDjNTVF4/88Z25dleqHj2F8+e0Fm7YVlyCNYNylwCjcB9zBkVc1QcAtn2dEpyPXjjsDTIoSNgmRNqaabCSLLUePzHxWnIm/P9leMpu8fCEofHptPV+GEOK1csVspKzi7xZT1fbXQlF0TsExPpv3RN390J7SrVJ2lZOVYn8jiJ1AMc9pWIRuC4blHTkYiZFyVsdqCcwMyMLpoTsSrH4WI/tts3o6Rp+FZmENf2cxtW267XThMjHZxvH9BOd+6EKcBruKV1ux7+ObQZmpCrV4KBPShUukMyruA/R6fvXsAlD70AUPj/cyCHB6HszyYrFarCckgUPaUtWa3IUWgMzyEI5inyllj+cxcm9c65WsObY+Ico=
    on:
        tags: true
        repo: tbodt/v8py
    distributions: sdist
    skip_upload_docs: true
