language: cpp
script: ./setup.py test

sudo: false
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5

install:
    - pip install --user twine pytest
    - export CFLAGS='-g -O0 --coverage'
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

# it takes ages to compile v8 so don't do it too often
cache:
    directories:
        - v8

after_success:
    - bash <(curl -s https://codecov.io/bash) -x gcov-5

deploy:
    provider: pypi
    user: tbodt
    password:
        secure: "KKVEq10cNqkFlSLlHidGUeGfjWTASOG8LXWOvuSnlpc9A4crHmtQLfJNkl7EEyyy3hcQY1r30Vq/baG3Iar60W3GYYD53ifewpSfeGUMqZN8Bfcl98Cu8T9XmTC4m+FP3k7ybFTh8KzgN/ivtUfHG8b50SVBccXqcro/Oh4VE8YryK/uhAFFV0hbuB4kURe5JVqO6lBo+4ssOyjKzFJ68kAkjry10yR7EtBW/+/4WpZGhLbhaDJCKWekGfwg8XR3PSg6zGJYSexRkJqJIoHq+PB/8yK/RusrAQXqWLb0fCEhMOkQWK+FBB41LWyayfMo7MhDQYv6GslkIu1eAeNitLFeT1wnb+0tVqVpIRsUhTNzzIASHq0zOeav8YriHHqdXd5xceRHPGu103k2ybceLg/I2ReRq2aO/yeJvC8IGL+2vhgN5UruvxxSWfo63ukRyqf9TEBZTIque6s9bFW/K+2wn7XDMNa1LBBcg+KKpDoXzqYc5oqJvjGMydJj+SfNo66aNaQ1WY2c0a+gA88B7+TaoWD6wOWquHHyCbGDGuuIbBw2n072FDwc4lP0dUa0zCOAKP15dTm6VO3xcuS2SMshQjAXgZ2hp4Z/cW5ghYiqwdfBZosT9gY/675o37Wdt80/lG8RWn0ByuM045pUjsYSCkBxzucMAzHTPPWYCxI="
    on:
        tags: true
        distributions: sdist bdist_wheel
        repo: tbodt/v8py
